NUMPY

In [1]:
import numpy as np

In [2]:
myarr=np.array([3,2,6,5])

In [3]:
myarr

array([3, 2, 6, 5])

In [4]:
zero=np.zeros((2,5))

In [5]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
rng=np.arange(15)

In [7]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
lpspace=np.linspace(1,5,10)

In [9]:
lpspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [10]:
ide=np.identity(15)

In [11]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [12]:
myarr.reshape(4,1)

array([[3],
       [2],
       [6],
       [5]])

In [14]:
myarr.shape

(4,)

PANDAS

In [15]:
import pandas as pd

In [16]:
dict1={"name":["rohan", "seema", "mahesh","shruti"],
       "marks":[90,80,70,60],
       "city":["pune","mumbai","nagpur","nashik"]}

In [20]:
df=pd.DataFrame(dict1)

In [21]:
print(df)

     name  marks    city
0   rohan     90    pune
1   seema     80  mumbai
2  mahesh     70  nagpur
3  shruti     60  nashik


In [22]:
df.index=[1,2,3,4]

In [23]:
df

name  marks    city
1   rohan     90    pune
2   seema     80  mumbai
3  mahesh     70  nagpur
4  shruti     60  nashik

In [24]:
ser=pd.Series(np.random.rand(20))

In [25]:
ser

0     0.333461
1     0.189026
2     0.277052
3     0.681609
4     0.128141
5     0.364046
6     0.762825
7     0.410376
8     0.303826
9     0.252926
10    0.283324
11    0.290176
12    0.646779
13    0.501889
14    0.736450
15    0.679057
16    0.381678
17    0.616101
18    0.811798
19    0.724390
dtype: float64

In [26]:
type(ser)

pandas.core.series.Series

In [27]:
newdf=pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

In [28]:
newdf

0         1         2         3         4
0    0.938592  0.601570  0.111307  0.248837  0.371304
1    0.181812  0.855285  0.501953  0.969116  0.396190
2    0.388362  0.998774  0.980512  0.749657  0.836590
3    0.154885  0.349005  0.400578  0.190702  0.048009
4    0.150009  0.294122  0.888692  0.904423  0.418416
..        ...       ...       ...       ...       ...
329  0.890846  0.609025  0.648049  0.871640  0.323589
330  0.653165  0.683662  0.185325  0.506670  0.549307
331  0.848165  0.895544  0.449027  0.230233  0.959972
332  0.523848  0.824551  0.772502  0.428748  0.029976
333  0.828796  0.028096  0.837717  0.154182  0.822582

[334 rows x 5 columns]

In [29]:
newdf.head(3)

0         1         2         3         4
0  0.938592  0.601570  0.111307  0.248837  0.371304
1  0.181812  0.855285  0.501953  0.969116  0.396190
2  0.388362  0.998774  0.980512  0.749657  0.836590

In [30]:
newdf.head(-3)

0         1         2         3         4
0    0.938592  0.601570  0.111307  0.248837  0.371304
1    0.181812  0.855285  0.501953  0.969116  0.396190
2    0.388362  0.998774  0.980512  0.749657  0.836590
3    0.154885  0.349005  0.400578  0.190702  0.048009
4    0.150009  0.294122  0.888692  0.904423  0.418416
..        ...       ...       ...       ...       ...
326  0.937868  0.258628  0.194955  0.143725  0.205851
327  0.539451  0.890633  0.820984  0.316883  0.067004
328  0.047982  0.442305  0.862192  0.151105  0.018986
329  0.890846  0.609025  0.648049  0.871640  0.323589
330  0.653165  0.683662  0.185325  0.506670  0.549307

[331 rows x 5 columns]

In [31]:
newdf.tail(3)

0         1         2         3         4
331  0.848165  0.895544  0.449027  0.230233  0.959972
332  0.523848  0.824551  0.772502  0.428748  0.029976
333  0.828796  0.028096  0.837717  0.154182  0.822582

In [32]:
newdf.sort_index(axis=0)

0         1         2         3         4
0    0.938592  0.601570  0.111307  0.248837  0.371304
1    0.181812  0.855285  0.501953  0.969116  0.396190
2    0.388362  0.998774  0.980512  0.749657  0.836590
3    0.154885  0.349005  0.400578  0.190702  0.048009
4    0.150009  0.294122  0.888692  0.904423  0.418416
..        ...       ...       ...       ...       ...
329  0.890846  0.609025  0.648049  0.871640  0.323589
330  0.653165  0.683662  0.185325  0.506670  0.549307
331  0.848165  0.895544  0.449027  0.230233  0.959972
332  0.523848  0.824551  0.772502  0.428748  0.029976
333  0.828796  0.028096  0.837717  0.154182  0.822582

[334 rows x 5 columns]

In [33]:
newdf.drop(0,axis=1)

1         2         3         4
0    0.601570  0.111307  0.248837  0.371304
1    0.855285  0.501953  0.969116  0.396190
2    0.998774  0.980512  0.749657  0.836590
3    0.349005  0.400578  0.190702  0.048009
4    0.294122  0.888692  0.904423  0.418416
..        ...       ...       ...       ...
329  0.609025  0.648049  0.871640  0.323589
330  0.683662  0.185325  0.506670  0.549307
331  0.895544  0.449027  0.230233  0.959972
332  0.824551  0.772502  0.428748  0.029976
333  0.028096  0.837717  0.154182  0.822582

[334 rows x 4 columns]

In [34]:
newdf.dropna(inplace=True)